source 'https://rubygems.org' do
  gem 'sinatra', '~> 2.0', '>= 2.0.3'
  gem 'httparty', '~> 0.16.2'
  gem 'sendgrid-ruby' 
  gem 'materialize', '~> 0.4.5'
  gem 'material_icons', '~> 2.2', '>= 2.2.1'
end